version: "3.9"

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    env_file:
      - .env
    ports:
      - "5433:5432"
    healthcheck:
      test: "pg_isready --username=${DB_USER} --database=${DB_NAME}"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

    networks:
      inteamnet:
        ipv4_address: 10.1.0.102

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env

    networks:
      inteamnet:
        ipv4_address: 10.1.0.100

networks:
  inteamnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
