version: "3.7"
services:
  db:
    image: postgres:16
    container_name: db
    env_file:
      - .env-non-dev
    command: -p 5432
    expose:
      - 5432
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: todo_app
    ports:
      - 2556:8000
    depends_on:
      - db